
services:
  db:
    image: postgres:15-alpine
    container_name: reqai_postgres
    environment:
      POSTGRES_USER: reqai_user
      POSTGRES_PASSWORD: reqai_password
      POSTGRES_DB: reqai_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: reqai_backend
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://reqai_user:reqai_password@db:5432/reqai_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    container_name: reqai_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata: