"""
End-to-End (E2E) Full System Test Suite for ReqAI

Tests complete user workflows:
1. Document Upload
2. AI Requirement Analysis & Task Decomposition (with multi-role validation: DEVELOPER, QA, etc.)
3. Document Detail & Tree Hierarchy Query
4. Test Scenario Status Update & Workflow Monitor State Persistence
5. System Analytics Metrics Retrieval
"""
import sys
import os

# Ensure backend directory is in sys.path
backend_path = os.path.join(os.path.dirname(__file__), 'backend')
if backend_path not in sys.path:
    sys.path.insert(0, backend_path)

# Set environment variables for standalone E2E testing using SQLite
os.environ["DATABASE_URL"] = "sqlite:///./test_reqai.db"
os.environ["USE_MOCK_AI"] = "true"

from fastapi.testclient import TestClient
from app.main import app

def run_e2e_tests():
    print("=" * 65)
    print("STARTING FULL END-TO-END (E2E) TEST SUITE FOR REQAI")
    print("=" * 65)

    client = TestClient(app)

    # -------------------------------------------------------------
    # Step 1: E2E Document Upload Test
    # -------------------------------------------------------------
    print("\n[STEP 1/5] Testing Document Upload Endpoint (/api/documents/upload)...")
    req_file_path = os.path.join(os.path.dirname(__file__), 'customer_requirements.txt')
    
    with open(req_file_path, 'rb') as f:
        response = client.post(
            "/api/documents/upload",
            files={"file": ("customer_requirements.txt", f, "text/plain")}
        )

    assert response.status_code in [200, 201], f"Upload failed with status {response.status_code}: {response.text}"
    doc_data = response.json()
    doc_id = doc_data["id"]
    print(f"  [OK] Document Uploaded Successfully! Doc ID: {doc_id}")
    print(f"  [OK] Status: {doc_data['status']}, Uploaded At: {doc_data['uploaded_at']}")

    # -------------------------------------------------------------
    # Step 2: E2E AI Requirement Analysis & Multi-Role Decomposition Test
    # -------------------------------------------------------------
    print("\n[STEP 2/5] Testing AI Requirement Analysis & Multi-Role Decomposition (/api/documents/{id}/analyze)...")
    analyze_res = client.post(f"/api/documents/{doc_id}/analyze")
    assert analyze_res.status_code == 200, f"Analysis trigger failed: {analyze_res.text}"
    
    # Execute analysis worker synchronously for test assertion
    from app.services.analysis_service import run_analysis_background
    run_analysis_background(doc_id)

    # Query analyzed document details
    detail_check = client.get(f"/api/documents/{doc_id}")
    assert detail_check.status_code == 200
    analyzed_doc = detail_check.json()

    assert analyzed_doc["status"] == "ANALYZED", f"Expected ANALYZED status, got {analyzed_doc['status']}"
    requirements = analyzed_doc.get("requirements", [])
    assert len(requirements) > 0, "No requirements were generated by AI Analysis!"
    
    print(f"  [OK] AI Analysis Completed Successfully! Generated Requirements: {len(requirements)}")

    # Verify Multi-Role Tasks (DEVELOPER, QA, DEVOPS, DESIGN, ANALYSIS)
    total_tasks = 0
    total_scenarios = 0
    detected_roles = set()

    for r_idx, req in enumerate(requirements):
        tasks = req.get("tasks", [])
        total_tasks += len(tasks)
        for t_idx, task in enumerate(tasks):
            role = task.get("role", "DEVELOPER")
            detected_roles.add(role)
            scenarios = task.get("test_scenarios", [])
            total_scenarios += len(scenarios)

    print(f"  [OK] Total Derived Tasks: {total_tasks}")
    print(f"  [OK] Total Test Scenarios: {total_scenarios}")
    print(f"  [OK] Detected Task Roles across requirements: {list(detected_roles)}")
    assert "DEVELOPER" in detected_roles or "QA" in detected_roles, "Expected DEVELOPER or QA role in decomposed tasks!"

    # -------------------------------------------------------------
    # Step 3: E2E Document Tree Hierarchy Query Test
    # -------------------------------------------------------------
    print("\n[STEP 3/5] Testing Document Detail Query (/api/documents/{id})...")
    detail_res = client.get(f"/api/documents/{doc_id}")
    assert detail_res.status_code == 200, f"Get detail failed: {detail_res.text}"
    detail_doc = detail_res.json()
    assert detail_doc["filename"] == "customer_requirements.txt"
    print("  [OK] Document Tree Detail Query Verified!")

    # -------------------------------------------------------------
    # Step 4: E2E Test Scenario Status Update Test
    # -------------------------------------------------------------
    print("\n[STEP 4/5] Testing Test Scenario Status Update (/api/documents/{id}/test-scenarios/{scenario_id})...")
    first_task = requirements[0]["tasks"][0]
    first_scenario = first_task["test_scenarios"][0]
    scenario_id = first_scenario["id"]

    update_payload = {
        "status": "PASSED",
        "comment": "E2E Automated Test: Verified test scenario execution successfully."
    }

    update_res = client.patch(
        f"/api/documents/{doc_id}/test-scenarios/{scenario_id}",
        json=update_payload
    )
    assert update_res.status_code == 200, f"Scenario update failed: {update_res.text}"
    updated_scenario = update_res.json()
    assert updated_scenario["status"] == "PASSED"
    assert updated_scenario["comment"] == update_payload["comment"]
    print(f"  [OK] Test Scenario {scenario_id[:8]}... Status Updated to PASSED with Comment!")

    # -------------------------------------------------------------
    # Step 5: E2E System Analytics Test
    # -------------------------------------------------------------
    print("\n[STEP 5/5] Testing System Analytics Endpoint (/api/documents/analytics)...")
    analytics_res = client.get("/api/documents/analytics")
    assert analytics_res.status_code == 200, f"Analytics failed: {analytics_res.text}"
    analytics_data = analytics_res.json()
    
    print(f"  [OK] Total Documents in System: {analytics_data['total_documents']}")
    print(f"  [OK] Total Requirements in System: {analytics_data['total_requirements']}")
    print(f"  [OK] Total Tasks in System: {analytics_data['total_tasks']}")
    print(f"  [OK] Total Test Scenarios in System: {analytics_data['total_test_scenarios']}")
    print(f"  [OK] Priority Distribution: {analytics_data['requirements_by_priority']}")
    print(f"  [OK] Complexity Distribution: {analytics_data['tasks_by_complexity']}")

    print("\n" + "=" * 65)
    print("[SUCCESS] ALL END-TO-END (E2E) INTEGRATION TESTS PASSED 100% SUCCESSFULLY!")
    print("=" * 65)

if __name__ == "__main__":
    run_e2e_tests()
